window.WEDDING_I18N = {
  vi: {
    loader:'Đang thắp đèn và trải lụa đỏ...', gateKicker:'Thiệp hỷ', gateTitle:'Tấn Phát & Hồng Ngọc', gateText:'Mở cổng son và bước vào một đêm trăng, sương và hoa đăng của chúng tôi.', openButton:'Mở thiệp', musicHint:'Nhạc sẽ phát sau khi mở thiệp', replayGate:'Xem lại cổng', clickHint:'Nhấn để mở cổng cung đình',
    navStory:'Câu chuyện', navEvent:'Hỷ sự', navTimeline:'Lịch trình', navGallery:'Ảnh cưới', navRsvp:'Xác nhận',
    heroBadgeSmall:'Song hỷ', heroBadgeStrong:'Hoa đăng nguyệt dạ', heroKicker:'Một giấc mộng cổ phong dịu dàng', heroTitle:'Tấn Phát <span>&</span> Hồng Ngọc', heroText:'Trân trọng kính mời bạn đến chung vui trong ngày hạnh phúc của chúng tôi — nơi trăng sáng, mây nhẹ và lời chúc phúc cùng hội tụ.', dateDay:'Chủ nhật', seeEvent:'Xem địa điểm', addCalendar:'Thêm vào lịch', saveDate:'Save the date',
    introKicker:'Mộng hoa đăng', introTitle:'Một lời mời dịu dàng giữa lụa đỏ, ánh trăng và làn sương mỏng.', introText:'Sự hiện diện của bạn là món quà quý giá nhất dành cho Tấn Phát và Hồng Ngọc trong ngày trọng đại này.', poemKicker:'Cổ phong', poemTitle:'Cổng son mở lối, hoa đăng dẫn đường.', poemText:'Giữa sắc đỏ hỷ sự và ánh vàng cung đăng, chúng tôi mong được cùng bạn lưu lại một đêm thật đẹp, thật ấm và thật đáng nhớ.',
    countKicker:'Đếm ngược', countTitle:'Ngày hẹn ước đang đến gần', days:'Ngày', hours:'Giờ', minutes:'Phút', seconds:'Giây',
    storyKicker:'Câu chuyện', storyTitle:'Từ một ánh nhìn, thành một đời bình yên.', storyText:'Chúng tôi đã chọn cùng nhau đi tiếp, để những ngày bình thường cũng trở thành kỷ niệm đẹp. Mong bạn sẽ đến chứng kiến khoảnh khắc chúng tôi bắt đầu một chương mới.', vowText:'Nguyện cùng nhau đi qua bốn mùa, giữ một mái nhà ấm, một tình yêu lành và một đời có nhau.',
    eventKicker:'Hỷ sự', eventTitle:'Thông tin ngày cưới', eventText:'Thời gian và địa điểm hiện đang để giả định, bạn có thể chỉnh sửa rất nhanh trong file HTML.', ceremonyTitle:'Lễ thành hôn', ceremonyTime:'17:30 — Chủ nhật, 22/11/2026', ceremonyPlace:'Tư gia nhà gái, Tân Bình, Thành phố Hồ Chí Minh', partyTitle:'Tiệc cưới', partyTime:'18:00 — Chủ nhật, 22/11/2026', partyPlace:'White Palace Hoàng Văn Thụ, 194 Hoàng Văn Thụ, Phú Nhuận, TP.HCM', openMap:'Mở bản đồ', dressTitle:'Dress code', dressText:'Trang phục thanh lịch với tông đỏ, vàng, trắng ngà để hòa cùng không gian Trung Hoa cổ phong.',
    timelineKicker:'Lịch trình', timelineTitle:'Một đêm hoa đăng dịu dàng', tl1Title:'Đón khách', tl1Text:'Chụp ảnh, ký tên lưu niệm và dùng tiệc nhẹ.', tl2Title:'Nghi thức cưới', tl2Text:'Trao nhẫn và nhận lời chúc phúc từ hai bên gia đình.', tl3Title:'Khai tiệc', tl3Text:'Dùng bữa tối cùng gia đình, bạn bè và người thân.', tl4Title:'Chung vui', tl4Text:'Nâng ly, âm nhạc và những bức ảnh thật đáng nhớ.',
    galleryKicker:'Ảnh cưới', galleryTitle:'Khoảnh khắc của chúng tôi', wishKicker:'Lời chúc', wishTitle:'Gửi lời chúc đến cô dâu chú rể', wishText:'Những lời chúc của bạn sẽ là kỷ niệm rất đẹp trong ngày trọng đại này.', yourName:'Tên của bạn', yourWish:'Lời chúc...', sendWish:'Gửi lời chúc',
    rsvpKicker:'Xác nhận', rsvpTitle:'Bạn sẽ đến chung vui chứ?', rsvpText:'Vui lòng xác nhận trước ngày 10/11/2026 để chúng tôi chuẩn bị chu đáo hơn.', contact:'Liên hệ', guestName:'Họ và tên', guestNamePlaceholder:'Nhập tên của bạn', guestCount:'Số khách tham dự', oneGuest:'1 khách', twoGuests:'2 khách', threeGuests:'3 khách', fourGuests:'4 khách', response:'Phản hồi', willAttend:'Tôi sẽ tham dự', cannotAttend:'Rất tiếc, tôi không tham dự được', note:'Lời nhắn', notePlaceholder:'Lời nhắn thêm...', confirm:'Xác nhận tham dự', footerText:'Cảm ơn bạn đã là một phần trong câu chuyện tình yêu của chúng tôi.',
    toastMusicMissing:'Chưa tìm thấy file nhạc. Hãy đặt MP3 tại assets/music/wedding-song.mp3.', toastWish:'Cảm ơn lời chúc thật đẹp của bạn!', toastRsvp:'Đã ghi nhận xác nhận tham dự trên trình duyệt này.', toastMusicOn:'Đã bật nhạc nền.', toastMusicOff:'Đã tắt nhạc nền.'
  },
  en: {
    loader:'Lighting lanterns and unfolding the red silk...', gateKicker:'Wedding invitation', gateTitle:'Tấn Phát & Hồng Ngọc', gateText:'Open the crimson gate and step into a moonlit night of mist, lanterns, and love.', openButton:'Open invitation', musicHint:'Music will play after opening the invitation', replayGate:'Replay the gate', clickHint:'Tap to open the palace gate',
    navStory:'Story', navEvent:'Wedding day', navTimeline:'Timeline', navGallery:'Gallery', navRsvp:'RSVP',
    heroBadgeSmall:'Double happiness', heroBadgeStrong:'Lanterns under moonlight', heroKicker:'A gentle dream in oriental romance', heroTitle:'Tấn Phát <span>&</span> Hồng Ngọc', heroText:'We warmly invite you to celebrate our special day with us — where moonlight, drifting clouds, and heartfelt blessings gather together.', dateDay:'Sunday', seeEvent:'View venue', addCalendar:'Add to calendar', saveDate:'Save the date',
    introKicker:'Lantern dream', introTitle:'A tender invitation wrapped in red silk, moonlight, and a veil of mist.', introText:'Your presence will be the most precious gift for Tấn Phát and Hồng Ngọc on this unforgettable day.', poemKicker:'Oriental romance', poemTitle:'The crimson gate opens, and lanterns light the way.', poemText:'Among wedding red and palace gold, we hope to share with you a night that feels warm, beautiful, and unforgettable.',
    countKicker:'Countdown', countTitle:'Our promised day is getting closer', days:'Days', hours:'Hours', minutes:'Minutes', seconds:'Seconds',
    storyKicker:'Our story', storyTitle:'From one glance to a lifetime of peace.', storyText:'We chose to keep walking together so that even ordinary days could become beautiful memories. We hope you will witness the beginning of our new chapter.', vowText:'We promise to walk through every season together, to keep a warm home, a kind love, and a lifetime by each other’s side.',
    eventKicker:'Wedding details', eventTitle:'Wedding information', eventText:'The date and venue below are temporary placeholders and can be edited quickly in the HTML file.', ceremonyTitle:'Ceremony', ceremonyTime:'17:30 — Sunday, 22/11/2026', ceremonyPlace:'Bride’s family home, Tan Binh, Ho Chi Minh City', partyTitle:'Reception', partyTime:'18:00 — Sunday, 22/11/2026', partyPlace:'White Palace Hoang Van Thu, 194 Hoang Van Thu, Phu Nhuan, Ho Chi Minh City', openMap:'Open map', dressTitle:'Dress code', dressText:'Elegant outfits in red, gold, and ivory are recommended to match the ancient Chinese-inspired atmosphere.',
    timelineKicker:'Timeline', timelineTitle:'A soft lantern night', tl1Title:'Guest welcome', tl1Text:'Take photos, sign the guestbook, and enjoy light refreshments.', tl2Title:'Wedding ritual', tl2Text:'Ring exchange and blessings from both families.', tl3Title:'Reception begins', tl3Text:'Dinner with family, friends, and loved ones.', tl4Title:'Celebration', tl4Text:'Raise a toast, enjoy music, and create unforgettable memories.',
    galleryKicker:'Gallery', galleryTitle:'Moments of us', wishKicker:'Best wishes', wishTitle:'Send your blessings to the bride and groom', wishText:'Your wishes will become a beautiful part of our wedding memories.', yourName:'Your name', yourWish:'Your message...', sendWish:'Send wishes',
    rsvpKicker:'RSVP', rsvpTitle:'Will you celebrate with us?', rsvpText:'Please confirm before 10/11/2026 so we can prepare more thoughtfully.', contact:'Contact', guestName:'Full name', guestNamePlaceholder:'Enter your name', guestCount:'Number of guests', oneGuest:'1 guest', twoGuests:'2 guests', threeGuests:'3 guests', fourGuests:'4 guests', response:'Response', willAttend:'I will attend', cannotAttend:'Sorry, I cannot attend', note:'Note', notePlaceholder:'Additional note...', confirm:'Confirm attendance', footerText:'Thank you for being part of our love story.',
    toastMusicMissing:'Music file not found. Please place your MP3 at assets/music/wedding-song.mp3.', toastWish:'Thank you for your beautiful wishes!', toastRsvp:'Your RSVP has been saved in this browser.', toastMusicOn:'Background music is on.', toastMusicOff:'Background music is off.'
  },
  'zh-CN': {
    loader:'正在点亮花灯，铺开红绸...', gateKicker:'喜帖', gateTitle:'Tấn Phát & Hồng Ngọc', gateText:'推开朱门，步入月色、薄雾与花灯交织的喜宴之夜。', openButton:'开启请柬', musicHint:'开启请柬后将播放音乐', replayGate:'重看开门', clickHint:'点击开启宫门',
    navStory:'故事', navEvent:'婚礼信息', navTimeline:'流程', navGallery:'婚纱照', navRsvp:'出席确认',
    heroBadgeSmall:'双喜', heroBadgeStrong:'花灯月夜', heroKicker:'一场温柔的东方古风梦', heroTitle:'Tấn Phát <span>&</span> Hồng Ngọc', heroText:'诚挚邀请您与我们一同见证幸福时刻——让月光、流云与真挚祝福在此相会。', dateDay:'星期日', seeEvent:'查看地点', addCalendar:'加入日历', saveDate:'谨记此日',
    introKicker:'花灯梦境', introTitle:'一封被红绸、月色与薄雾温柔包裹的请柬。', introText:'您的到来，将会是 Tấn Phát 与 Hồng Ngọc 在这重要日子里最珍贵的礼物。', poemKicker:'古风', poemTitle:'朱门启路，花灯引梦。', poemText:'在喜红与宫灯金色之间，愿与您一同留下温暖、美好且难忘的一夜。',
    countKicker:'倒计时', countTitle:'约定之日正在靠近', days:'天', hours:'小时', minutes:'分钟', seconds:'秒',
    storyKicker:'我们的故事', storyTitle:'从一眼心动，到一生安稳。', storyText:'我们选择携手同行，让平凡的日子也成为珍贵回忆。愿您见证我们新篇章的开始。', vowText:'愿与君共度四季，守一方温暖的家，一份温柔的爱，一生相伴。',
    eventKicker:'喜事', eventTitle:'婚礼信息', eventText:'以下时间与地点为暂定内容，可在 HTML 文件中快速修改。', ceremonyTitle:'成婚礼', ceremonyTime:'17:30 — 2026年11月22日 星期日', ceremonyPlace:'新娘家，Tân Bình，胡志明市', partyTitle:'婚宴', partyTime:'18:00 — 2026年11月22日 星期日', partyPlace:'White Palace Hoàng Văn Thụ，194 Hoàng Văn Thụ，Phú Nhuận，胡志明市', openMap:'打开地图', dressTitle:'着装建议', dressText:'建议选择红色、金色、象牙白等优雅色系，以融入中式古风氛围。',
    timelineKicker:'流程', timelineTitle:'一夜温柔花灯', tl1Title:'迎宾', tl1Text:'合影、签到留念与茶点。', tl2Title:'婚礼仪式', tl2Text:'交换戒指，接受双方家人的祝福。', tl3Title:'开宴', tl3Text:'与家人、朋友和亲人共享晚宴。', tl4Title:'同庆', tl4Text:'举杯、音乐与难忘的照片。',
    galleryKicker:'婚纱照', galleryTitle:'我们的瞬间', wishKicker:'祝福', wishTitle:'给新人送上祝福', wishText:'您的祝福会成为婚礼最美好的回忆之一。', yourName:'您的姓名', yourWish:'您的祝福...', sendWish:'送出祝福',
    rsvpKicker:'出席确认', rsvpTitle:'您会来和我们一同庆祝吗？', rsvpText:'请在 2026年11月10日前确认，以便我们更周到地准备。', contact:'联系', guestName:'姓名', guestNamePlaceholder:'请输入您的姓名', guestCount:'出席人数', oneGuest:'1位', twoGuests:'2位', threeGuests:'3位', fourGuests:'4位', response:'回复', willAttend:'我会出席', cannotAttend:'很抱歉，我无法出席', note:'留言', notePlaceholder:'补充留言...', confirm:'确认出席', footerText:'感谢您成为我们爱情故事的一部分。',
    toastMusicMissing:'未找到音乐文件。请把 MP3 放到 assets/music/wedding-song.mp3。', toastWish:'感谢您的美好祝福！', toastRsvp:'您的出席确认已保存在此浏览器中。', toastMusicOn:'背景音乐已开启。', toastMusicOff:'背景音乐已关闭。'
  },
  'zh-TW': {
    loader:'正在點亮花燈，鋪開紅綢...', gateKicker:'喜帖', gateTitle:'Tấn Phát & Hồng Ngọc', gateText:'推開朱門，步入月色、薄霧與花燈交織的喜宴之夜。', openButton:'開啟請柬', musicHint:'開啟請柬後將播放音樂', replayGate:'重看開門',
    navStory:'故事', navEvent:'婚禮資訊', navTimeline:'流程', navGallery:'婚紗照', navRsvp:'出席確認',
    heroBadgeSmall:'雙喜', heroBadgeStrong:'花燈月夜', heroKicker:'一场温柔的東方古風夢', heroTitle:'Tấn Phát <span>&</span> Hồng Ngọc', heroText:'誠摯邀請您與我們一同見證幸福時刻——讓月光、流雲與真摯祝福在此相會。', dateDay:'星期日', seeEvent:'查看地點', addCalendar:'加入日曆', saveDate:'謹記此日',
    introKicker:'花燈夢境', introTitle:'一封被紅綢、月色與薄霧温柔包裹的請柬。', introText:'您的到來，將會是 Tấn Phát 與 Hồng Ngọc 在這重要日子里最珍貴的禮物。', poemKicker:'古風', poemTitle:'朱門啟路，花燈引夢。', poemText:'在喜紅與宮燈金色之間，願與您一同留下温暖、美好且難忘的一夜。',
    countKicker:'倒計時', countTitle:'约定之日正在靠近', days:'天', hours:'小時', minutes:'分鐘', seconds:'秒',
    storyKicker:'我們的故事', storyTitle:'從一眼心動，到一生安穩。', storyText:'我們選擇攜手同行，讓平凡的日子也成為珍貴回憶。願您見證我們新篇章的開始。', vowText:'願與君共度四季，守一方温暖的家，一份温柔的愛，一生相伴。',
    eventKicker:'喜事', eventTitle:'婚禮資訊', eventText:'以下時間與地點為暫定內容，可在 HTML 文件中快速修改。', ceremonyTitle:'成婚禮', ceremonyTime:'17:30 — 2026年11月22日 星期日', ceremonyPlace:'新娘家，Tân Bình，胡志明市', partyTitle:'婚宴', partyTime:'18:00 — 2026年11月22日 星期日', partyPlace:'White Palace Hoàng Văn Thụ，194 Hoàng Văn Thụ，Phú Nhuận，胡志明市', openMap:'打開地圖', dressTitle:'着装建議', dressText:'建議選擇紅色、金色、象牙白等優雅色系，以融入中式古風氛圍。',
    timelineKicker:'流程', timelineTitle:'一夜温柔花燈', tl1Title:'迎賓', tl1Text:'合影、簽到留念與茶點。', tl2Title:'婚禮儀式', tl2Text:'交換戒指，接受雙方家人的祝福。', tl3Title:'開宴', tl3Text:'與家人、朋友和親人共享晚宴。', tl4Title:'同慶', tl4Text:'舉杯、音樂與難忘的照片。',
    galleryKicker:'婚紗照', galleryTitle:'我們的瞬間', wishKicker:'祝福', wishTitle:'給新人送上祝福', wishText:'您的祝福會成為婚禮最美好的回憶之一。', yourName:'您的姓名', yourWish:'您的祝福...', sendWish:'送出祝福',
    rsvpKicker:'出席確認', rsvpTitle:'您會來和我們一同慶祝嗎？', rsvpText:'請在 2026年11月10日前確認，以便我們更周到地准備。', contact:'聯系', guestName:'姓名', guestNamePlaceholder:'請輸入您的姓名', guestCount:'出席人数', oneGuest:'1位', twoGuests:'2位', threeGuests:'3位', fourGuests:'4位', response:'回覆', willAttend:'我會出席', cannotAttend:'很抱歉，我无法出席', note:'留言', notePlaceholder:'補充留言...', confirm:'確認出席', footerText:'感谢您成為我們愛情故事的一部分。',
    toastMusicMissing:'未找到音樂文件。請把 MP3 放到 assets/music/wedding-song.mp3。', toastWish:'感谢您的美好祝福！', toastRsvp:'您的出席確認已保存在此瀏覽器中。', toastMusicOn:'背景音樂已開啟。', toastMusicOff:'背景音樂已关閉。'
  }
};